# Generated by Django 5.2.3 on 2025-06-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_question_question_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
