# Generated by Django 5.2.3 on 2025-06-19 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_profile_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='project.question'),
        ),
    ]
