# Generated by Django 5.2.3 on 2025-06-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_questionchoice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaattempt',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('history', 'History'), ('geography', 'Geography')]),
        ),
    ]
