# Generated by Django 5.2.3 on 2025-06-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_triviaattempt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('History', 'History'), ('Geography', 'Geography')]),
        ),
        migrations.AlterField(
            model_name='triviaattempt',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('History', 'History'), ('Geography', 'Geography')]),
        ),
    ]
