# Generated by Django 5.2.3 on 2025-06-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_question_category_alter_triviaattempt_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admin_user',
        ),
    ]
